debian/tmp/etc/dbus-1/system.d/ConsoleKit.conf
debian/tmp/etc/ConsoleKit/
debian/tmp/usr/share/dbus-1/system-services/
debian/tmp/usr/share/polkit-1/
debian/tmp/usr/lib/ConsoleKit/
debian/tmp/var/log/ConsoleKit/
debian/tmp/usr/sbin/
debian/tmp/usr/bin/
debian/90consolekit etc/X11/Xsession.d/
debian/tmp/lib/systemd/system/console-kit-daemon.service
debian/tmp/lib/systemd/system/console-kit-log-system-start.service
debian/tmp/lib/systemd/system/console-kit-log-system-stop.service
debian/tmp/lib/systemd/system/console-kit-log-system-restart.service
debian/tmp/lib/systemd/system/basic.target.wants/console-kit-log-system-start.service
debian/tmp/lib/systemd/system/halt.target.wants/console-kit-log-system-stop.service
debian/tmp/lib/systemd/system/poweroff.target.wants/console-kit-log-system-stop.service
debian/tmp/lib/systemd/system/reboot.target.wants/console-kit-log-system-restart.service
